package ir.hoshmand.zamin.iran.wheatdisease.models;


import android.content.Context;
import android.support.v4.content.ContextCompat;
import android.view.MotionEvent;

import java.util.ArrayList;

import ir.hoshmand.zamin.iran.wheatdisease.R;

public class DataHandler {
    public static ArrayList<MenuItem> disease;

    public DataHandler(Context context) {
        MenuItem menuItem = new MenuItem("زنگ زرد (نواری) گندم", ContextCompat.getDrawable(context, R.drawable.img_0));
        Title title = new Title("شرح");
        title.addLevel("زنگ زرد مهمترین بیماری گندم محسوب می شود و در صورت همه جا گیر شدن می تواند بسیار خطرناک باشد");
        title.addLevel("دمای بهینه رشد 13-8 درجه سانتی گراد است.");
        title.addLevel("•\tبه محض گرم شدن هوا  از میزان خسارت آن کاسته می شود.");
        menuItem.addTitle(title);
        title = new Title("شرایط همه گیر شدن بیماری");
        title.addLevel("عوامل محیطی موثر در بروز و توسعه بیماری زنگ زرد عبارتند از: ارقام حساس، درجه حرارت، رطوبت مناسب و علفهای هرز میزبان");
        title.addLevel("گندم های مزارع دیر کاشت واقع در مناطق مرتفع، گندمهای خودرو حاصل از ریزش بذر در موقع برداشت و علفهای هرز میزبان در حاشیه مزارع به عنوان پل سبز باعث انتقال بیماری از فصلی به فصل دیگر می شوند.");
        title.addLevel("در صورت مساعد بودن شرایط محیطی آلودگی اولیه در پاییز اتفاق می افتد.");
        title.addLevel("درجه حرارت در زمستان نقش عمده ای در شروع اپیدمی زنگ زرد در بهار دارد.");
        title.addLevel("اگر زمستان معتدل باشد و در اوایل فصل بهار شرایط محیطی مناسب باشد (نظیر بارندگیهای زیاد توام با دمای مناسب 13-8 درجه سانتی گراد) و ارقام مورد کشت حساس باشند احتمال اپیدمی شدن بیماری زیاد خواهد بود.");
        title.addLevel("هرچقدر درجه حرارت در طول ماه های زمستان پایین تر و مدت سرما طولانی تر باشد بروز و توسعه آلودگی کند تر خواهد بود.");
        menuItem.addTitle(title);
        title = new Title("روش های کنترل زنگ زرد");
        title.addLevel("روشهای زراعی");
        title.addLevel("خوداری از کشت زود هنگام در پاییز (در ارقام زمستانه)");
        title.addLevel("از بین بردن گندم های خود رو پس از برداشت و همچنین علفهای هرز میزبان ( پل سبز و انتقال بیماری از فصلی به فصل دیگر)");
        title.addLevel("استفاده از ارقام زود رس بهاره یا کشت زود هنگام آنها");
        title.addLevel("ازت مورد نیازدر دو یا سه نوبت استفاده شود.");
        menuItem.addTitle(title);
        title = new Title("استفاده از ارقام مقاوم");
        title.addLevel("اقلیم گرم و مرطوب شمال: ارقام مروارید، گنبد، شیرودی، آرتا، دریا  و N-87-20 (احسان)");
        title.addLevel(" اقلیم سرد کشور: ارقام زارع، پیشگام، الوند، اروم، میهن و حیدری");
        title.addLevel("  اقلیم معتدل کشور: ارقام پارسی، بهار، سیوند و سیروان ");
        title.addLevel("اقلیم گرم و خشک جنوب: افلاک، مهرگان، چمران 2");
        menuItem.addTitle(title);
        title = new Title("ردیابی و کانون کوبی بیماری");
        title.addLevel("بازدید مرتب از مزارع در پاییز و اوایل بهار بطور هفتگی  و پس از ساقه دهی هفته ای دوبار");
        title.addLevel("شرایط آب و هوایی: میانگین درجه حرارت بین 10 تا 15 درجه سانتی گراد و میانگین رطوبت بیش از 70% باشد");
        title.addLevel("آستانه اقتصادی: به محض ظهور علایم بیماری وتشکیل اولین پوستولهای بیماری بصورت تک ردیفی");
        title.addLevel("با قارچکشهای توصیه شده کانون کوبی شود.");
        menuItem.addTitle(title);
        title = new Title("قارچکشهای توصیه شده برای کنترل زنگ زرد");
        title.addLevel("فالكن EC 46%  0/6 ليتر در هكتار. (تبوکونازول+تریادیمینول+اسپیروکسامین)");
        title.addLevel("آميستار اكسترا SC 28% ، 0/75 ليتر در هكتار");
        title.addLevel("آلتو (سیپرکونازول) SL 10%، 0/5 ليتر در هكتار. ");
        title.addLevel("فوليكور (تبوکونازول)EW 25% ، 1 ليتر در هكتار.");
        title.addLevel("ايمپكت (فلوتریافول) SC 12.5%، 1 ليتر در هكتار.");
        title.addLevel("آرتئا EC 33%(پروپیکونازول+سیپرکونازول)، 0/3 ليتر در هكتار");
        title.addLevel("تيلت EC 25% (پروپیکونازول)، 0/5 ليتر در هكتار کارآیی کم دارد.");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("زنگ قهوه ای", ContextCompat.getDrawable(context, R.drawable.img_1));
        title = new Title("شرح");
        title.addLevel("گسترش آن از زنگ زرد و سیاه در عرصه جهانی بیشتر است.");
        title.addLevel("بهترین دمای رشد 20-15 درجه سانتی گراد است");
        title.addLevel("این بیماری در اغلب نقاط کشور بویژه در مناطق غرب و شمالغرب کشور خسارت می زند.");
        title.addLevel("این بیماری در مزارعی که دیر کشت شده باشند و یا در گندمهای بهاره خسارت زیادی می زند ولی به محض گرم شدن هوا از شدت بیماری کاسته می شود");
        menuItem.addTitle(title);
        title = new Title("روش های کنترل زنگ قهوه ای");
        title.addLevel("خوداری از کشت زودهنگام در پاییز (در ارقام زمستانه)");
        title.addLevel("از بین بردن گندم های خود رو پس از برداشت و همچنین علفهای هرز میزبان");
        title.addLevel("استفاده از ارقام زود رس بهاره یا کشت زود هنگام آنها");
        title.addLevel("ازت مورد نیازدر دو یا سه نوبت استفاده شود.");
        title.addLevel("استفاده از ارقام مقاوم نظیر: مروارید، گنبد، زارع، اروم ،پیشگام، میهن ، سیروان و افلاک");
        title.addLevel("آستانه اقتصادی: به محض ظهور علایم در سه برگ انتهایی کانون کوبی با استفاده از قارچکشهای توصیه شده");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("زنگ سیاه گندم", ContextCompat.getDrawable(context, R.drawable.img_2));
        title = new Title("شرح");
        title.addLevel("عمدتا در آخر فصل زراعی همزمان با گرم شدن هوا گسترش می یابد.");
        title.addLevel("دمای مطلوب توسعه بیماری 25 درجه سانتی گراد است.");
        title.addLevel("خسارت اين بيماري در سالهاي 1345-1343 در مناطق شمالي كشور و در سال 1355 در مناطق جنوبي كشور خسارت سنگيني را به كشاورزان وارد نمود");
        title.addLevel(" اما در دهه های اخیر بدلیل استفاده از ارقام مقاوم (Sr31)  خسارت آن ناچیز بود.");
        menuItem.addTitle(title);
        title = new Title("مدیریت زنگ  سیاه گندم ");
        title.addLevel("تحت نظر داشتن بیماری در تمام مناطق کشور");
        title.addLevel("ردیابی و کانون کوبی دقیق بیماری");
        title.addLevel("کنترل شمیایی با استفاده از قارچکشهای توصیه شده");
        title.addLevel("استفاده از ارقام مقاوم متناسب با نوع اقلیم: مروارید، گنبد، پارسی، سیوند، سیروان و مهرگان");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem(, "سفيدك پودري گندم ", ContextCompat.getDrawable(context, R.drawable.img_3));
        title = new Title("اهمیت بیماری");
        title.addLevel("در پاره ای از مناطق کشور بویژه در استانهای گلستان، مازندران، خراسان رضوی و شمالی، اردبیل و تهران (ورامین) خسارت قابل توجهی میزند.");
        title.addLevel("عامل بیماری قارچ  Blumeria graminis f.sp.  tritici ");
        title.addLevel("انگل اجباري بوده و بر روي ميزبانان خود با فرم هاي اختصاصي بيماريزايي دارد . علاوه بر گندم روی Aegilops و َAgropyron ايجاد بيماری ميکند. ");
        title.addLevel("باعث کاهش فتوسنتز و افزایش تنفس گیاه می گردد و اندوخته غذایی گیاه هدر می رود. ");
        title.addLevel("در شرایط رطوبت و خشکی متناوب گسترش می یابد.");
        title.addLevel("در مزارعی که تراکم کاشت بالایی داشته و از کود های ازته زیاد استفاده شده باشد بیشتر است.");
        title.addLevel("فرم جنسی قارچ باعث دوام بیماری از فصلی به فصل دیگر می شود.");
        menuItem.addTitle(title);

        title = new Title("روش های زراعي ");
        title.addLevel("خوداری از کاشت متراکم بذر");
        title.addLevel("خود داری از مصرف زیاد کودهای ازته  و استفاده آنها در سه نوبت");
        title.addLevel("اجتناب از کاشت ارقام حساس و استفاده از ارقام مقاومی نظیر پیشتاز ، الوند، مغان.");
        title.addLevel("ارقامی که در پدیگری خود Appolo   را دارند مقاوم هستند.");
        title.addLevel("بازدید مرتب مزرعه (هفته ای یکبار) از شروع ساقه دهی و در صورت وجود آلودگی در 20% سه برگ انتهایی با شدت آلودگی  5%سمپاشی شود.");
        title.addLevel("قارچکشهای توصیه شده تیلت به میزان 1 لیتر و ایمپکت آر 25/1 تا 5/1 لیتر در هکتار");
        menuItem.addTitle(title);
        disease.add(menuItem);
        menuItem = new MenuItem("سپتوريوز برگ گندم قارچ عامل بيماري Zymoseptoria tritici", ContextCompat.getDrawable(context, R.drawable.img_4));
        title = new Title("شرايط مناسب براي اپيدمي شدن بيماري");
        title.addLevel("دماي خنك ( ˚C 20-15)");
        title.addLevel("رطوبت زياد توام با بارندگيهاي مكرر ");
        title.addLevel("در برخی سالها در استانهاي گلستان، مازندران، كرمانشاه، خوزستان، ایلام، خراسان رضوی و شمالی، فارس و اردبيل گسترش یافته است.");
        title.addLevel("بقایای گیاهی آلوده باعث دوام و انتقال بیماری از سالی به سال دیگر است.");
        menuItem.addTitle(title);
        title = new Title("روشهاي كنترل سپتوريوز برگ");
        title.addLevel("رعايت تناوب زراعي با گیاهان غیر گندمیان");
        title.addLevel("جمع آوری بقایای گیاهی در مناطق آلوده و معدوم نمودن آنها");
        title.addLevel("بازدید مرتب از مزارع پس از شروع ساقه دهی");
        title.addLevel("آستانه اقتصادی: آلودگی20% سه برگ انتهایی با شدت آلودگی 5%");
        title.addLevel("•سمپاشی با  قارچكشهایي نظیر آلرت 4/. لیتر، ایمپکت آر 5/1-25/1 و فولیکور یک لیتر در هکتار ");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("لكه خرمایی (Tan spot)", ContextCompat.getDrawable(context, R.drawable.img_5));
        title = new Title("شرح");
        title.addLevel("قارچ عامل بيماري Drechslera tritici-repentis     ");
        title.addLevel("فرم جنسي Pyrenophora tritici-repentis  ");
        title.addLevel("در مناطق گلستان، مازندران و اخیرا اردبیل (بیله سوار)  گسترش پیدا کرده است ");
        title.addLevel("از بين بردن بقاياي گياهي ");
        title.addLevel("رعايت تناوب زراعي  ");
        title.addLevel("ضدعفوني بذر با سموم موثر نظير ترياديمنول  ");
        title.addLevel("استفاده از ارقام مقاوم نظیر مروارید");
        title.addLevel("بازدید مرتب مزارع از مرحله شروع ساقه دهی و در صورت 20% آلودگی در سه برگ انتهایی. حداقل 20 نقطه مزرعه بصورت تصادفی بازدید شود.");
        title.addLevel(" سمپاشي با فالکن 75/. لیتر در هکتار و ناتیو به میزان 25/1 لیتر در هکتار");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("بیماری لکه نواری باکتریایی برگ گندم", ContextCompat.getDrawable(context, R.drawable.img_6));
        title = new Title("شرح");
        title.addLevel("عامل بیماری باکتری Xanthomonas translucens pv. undulosa");
        title.addLevel("متاسفانه در سال 1396 بدلیل بارندگی های بهاره و  وجود ارقام حساس ، در مناطقی از استانهای لرستان، همدان، زنجان، کردستان، خراسان رضوی و چهار محال بختیاری اپیدمی گردید.");
        title.addLevel("این بیماری از سالها قبل به صورت اندمیک در اغلب مناطق کشور وجود داشت ولی اهمیت چندانی نداشت.");
        title.addLevel("بیشتر در مزارعی که از آبیاری بارانی استفاده شده بود مشاهده گردید.");
        title.addLevel("در سالهای اخیر در ایالتهای شمالی آمریکا نیز نظیر مینوسوتا، داکوتای شمالی و جنوبی و مونتانا خسارت می زند. ");
        menuItem.addTitle(title);
        title = new Title("علایم بیماری باکتریایی نواری برگ گندم");
        title.addLevel("علایم اولیه بصورت لکه های نواری (خطی) روشن و آبسوخته در سطح برگ دیده می شود.");
        title.addLevel("در روی برگهای آلوده ترشحات شیری رنگ باکتری در اوایل صبح دیده می شود");
        title.addLevel("در حالت پیشرفته لکه های آبسوخته اغلب سطح برگ را فرا می گیرد.");
        title.addLevel("علائم بیماری روی سنبله ها بصورت سوختگی پوشینه ها دیده می شود و اصطلاحا Black chaff گفته می شود. ");
        title.addLevel("در روی پوشینه ها لکه های آبسوخته عمدتا در قسمت پایین به رنگ قهو ه ای  بصورت گریس زده شده دیده می شود.");
        title.addLevel("برخی ازارقام نظیر پیشگام و میهن بسیار حساس می باشند.");
        title.addLevel("برخی از ارقام نظیر الوند کمتر آلوده می شوند.");
        title.addLevel("علائم بیماری عمدتا روی برگ  و گاهی در روی سنبله ها مشاهده گردید.");
        title.addLevel("علاوه بر گندم روی جو، چاودار و علفهای هرز گرامینه ایجاد بیماری می کند.");
        title.addLevel("بیماری در بقایای گیاهی و بذر و علفهای هرز گرامینه دوام می آورد.");
        menuItem.addTitle(title);
        title = new Title("روش های مدیریت بیماری باکتریایی نواری گندم");
        title.addLevel("استفاده از بذر سالم و گواهی شده (از مزارعی که آلودگی نشان می دهند بذر تهیه نگردد.)");
        title.addLevel("رعایت تناوب با گیاهان غیر گرامینه");
        title.addLevel("استفاده از روش آبیاری مناسب (آبیاری بارانی مناسب نیست)");
        title.addLevel("مدیریت بقایای گیاهی");
        title.addLevel("خودداری از کاشت ارقام حساس نظیر پیشگام و میهن در مناطق آلوده");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("بیماری کپک برفی (snow mold)", ContextCompat.getDrawable(context, R.drawable.img_7));
        title = new Title("شرح");
        title.addLevel("عامل بیماری قارچ  Microdochium nivale  و M. majus");
        title.addLevel("علایم بیماری بصورت لکه های آبسوخته در روی برگ");
        title.addLevel("در روی خوشه ها نیز علائم شبیه فوزاریوم تولید می کند.");
        title.addLevel("ارقام گندم دوروم حساس هستند.");
        title.addLevel("مناطق پراکنش: استانهای گلستان، مازندران و خوزستان می باشد");
        menuItem.addTitle(title);
        title = new Title("روش های مدیریت بیماری کپک برفی گندم");
        title.addLevel("در مناطق آلوده گندم بعد از ذرت، ذرت خوشه ای و گندم  کشت نشود.");
        title.addLevel("ضد عفونی بذر بدقت انجام شود، بیماری بذر زاد است.");
        title.addLevel("در ایران قارچکشی برای کنترل این بیماری به ثبت نرسیده است. ");
        title.addLevel("در منابع قارچکش پروتیوکونازول (PROSARO) برای کنترل این بیماری توصیه شده است.");
        menuItem.addTitle(title);
        disease.add(menuItem);
        menuItem = new MenuItem("فوزاریوم سنبله گندم (FHB)", ContextCompat.getDrawable(context, R.drawable.img_7));
        title = new Title("شرح");
        title.addLevel("توسط چندین گونه ایجاد می شود: گونه غالب (Fusarium graminearum) ");
        title.addLevel("فوزاریوم خوشه یکی از بیماریهای مهم گندم در کشور است و در بعضی از استانها از جمله گلستان، مازندران و اردبیل (مغان)  خیلی خسارت می زند");
        title.addLevel("اين بيماري علاوه بر كاهش عملکرد گندم، چند زهرابه قارچی (مايكوتوكسين) خطرناك در دانههاي آلوده توليد ميكند كه براي سلامت انسان، دام و طيور بسيار مضرند.");
        title.addLevel("بارندگی و رطوبت بالا در مرحله گلدهي در شیوع بیماری نقش مهمی دارد.");
        menuItem.addTitle(title);
        title = new Title("علائم بیماری فوزاریوم خوشه گندم");
        title.addLevel("ايجاد يك لكه كوچك آب سوخته و كم و بيش قهوه اي رنگ، وسط گلوم يا روي محور سنبله");
        title.addLevel("سفید شدن سنبلچه هاي آلوده قبل از بلوغ");
        title.addLevel("رشد ميسليومي صورتي در روی سنبله");
        title.addLevel("دانه هاي گندم آلوده اغلب چروكيده، پوك و لاغر هستند");
        title.addLevel("تولید مایکوتوکسین (زهرابه) DON می کند که برای سلامتی انسان و دام مضر هستند.");
        title.addLevel("حد مجاز استاندارد دان در گندم 1 پی پی ام است");
        menuItem.addTitle(title);
        title = new Title("مدیریت بیماری فوزاریوم خوشه ");
        title.addLevel("محصول قبلی در شیوع بیماری خیلی مهم است.");
        title.addLevel("ذرت، ذرت خوشه ای، گرامینه ها نباید در تناوب با گندم قرار داده شوند چون میزبان قارچ هستند.");
        title.addLevel("رعایت تناوب با گیاهان غیر میزبان نظیر: سویا، کلزا، عدس، چغندر قند، پنبه، شبدر، نخود، آفتابگردان و ...");
        title.addLevel("مدیریت بقایای گندم در مناطق آلوده به بیماری (خرد کردن ودفن در خاک");
        title.addLevel("استفاده از ارقام متحمل نظیر مروارید و گنبد");
        title = new Title("استفاده از جدول تحلیل خطر و پیش آگاهی وقوع بیماری");
        title.addLevel("اطلاع از محصول کاشته شده قبلی: ذرت، ذرت خوشه ای  بیشترین خطر را دارد.");
        title.addLevel("نوع عملیات خاک ورزی انجام شده پس از برداشت محصول قبلی: اگر بقایا خرد و زیر خاک مدفون شده باشد خطر وقوع کمتر است اما اگر بقایا در سطح خاک مانده باشند خطر وقوع افزایش می یابد.");
        title.addLevel("حساسیت رقم کشت شده (در ارقام متحمل خطر وقوع کمتر است)");
        title.addLevel("شرایط آب و هوایی: میزان بارندگی یک هفته قبل و بعد از گل دهی بیش از 40 میلی متر باشد حتما بایستی سمپاشی شود. ");
        title.addLevel("استفاده از مدلهای پیش آگاهی نظیر DON cast RATFHB, ");
        menuItem.addTitle(title);
        title = new Title("کنترل شیمیایی بیماری ");
        title.addLevel("بهترین زمان سمپاشی در مرحله شروع گلدهی است.");
        title.addLevel("سمپاشی بعد از ظهور علایم فایده ای ندارد و خیلی دیر شده است.");
        menuItem.addTitle(title);
        title = new Title("استفاده از قارچکشهای موثر نظیر");
        title.addLevel("آلتوکمبی به میزان 5/. لیتر در هکتار");
        title.addLevel(" فالکن 7/. لیتر در هکتار");
        title.addLevel(" ركس دو 7/0-5/0 ليتر در هکتار");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("سپتوريوز سنبله گندم", ContextCompat.getDrawable(context, R.drawable.img_8));
        title = new Title("شرح");
        title.addLevel("قارچ عامل بيماري در مناطق گرم و مرطوب بيشتر خسارت مي زند.");
        title.addLevel("در سال 1381 از استان گلستان و اخیرا از استان خوزستان، فارس و کهکیلویه و بویر احمد گزارش گرديده است.");
        title.addLevel("علائم بيماري روي برگ ، ساقه، ميانگره ها و گلوم تشكيل مي شود.");
        title.addLevel("قارچ عامل بيماري بذر زاد است و بسهولت از طريق بذر از مناطق آلوده به ساير مناطق منتقل مي شود. ");
        menuItem.addTitle(title);
        title = new Title("روشهاي كنترل بيماري سپتوريوز سنبله");
        title.addLevel("استفاده از بذور گواهی شده و عاری از بیماری");
        title.addLevel("ضد عفوني بذر با قارچكشهاي موثر");
        title.addLevel("رعايت تناوب زراعي");
        title.addLevel("استفاده از ارقام مقاوم");
        title.addLevel("جمع آوري بقاياي گياهي يا شخم عميق یا چرانیدن بقایای محصول");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("سیاهک آشکار گندم", ContextCompat.getDrawable(context, R.drawable.img_9));
        title = new Title("شزح");
        title.addLevel("عامل بیماری Ustilago tritici ");
        title.addLevel("بیشتر در مناطق سرد و مرطوب شایع است. ");
        title.addLevel("بوته های سیاهک زده زودتر به خوشه می روند ");
        title.addLevel("سنبله آلوده تبدیل به یک توده سیاهک می شود که از اسپور های زیتونی تشکیل یافته است که با یک غشای خاکستری پوشیده شده اند ولی زود می ترکند و اسپور ها در هوا پخش می شوند و فقط محور مرکزی خو شه باقی می ماند. ");
        menuItem.addTitle(title);
        title = new Title("مدیریت سیاهک آشکار گندم");
        title.addLevel("كاشت بذر سالم و عاري از بيماري");
        title.addLevel("- ضد عفوني دقیق بذور با استفاده از قارچهاي زیر: \n" +
                "ويتاواكس تيرام ((FL 40% 2 ليتر براي يك تن بذر ،راكسيل (FS 6%) 5/0 ليتر براي يك تن بذر، ديويدند (DS 3%) 1 كيلوگرم براي يك تن بذر ، سومي ايت ((WP 2% 2 كيلوگرم براي يك تن بذر، بايتان ((DS 7.5% 2 كيلوگرم براي يك تن بذر ، وينسيتپي ((DS 5% 2 كيلوگرم براي يك تن بذر ،باويستين DS 60%)) 2 كيلوگرم براي يك تن بذر \n");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("سیاهک پنهان معمولی", ContextCompat.getDrawable(context, R.drawable.img_10));
        title = new Title("شرح");
        title.addLevel("سـيـاهـك پـنـهـان گـنـدم توسط دو گــونه قارچ: Tilletia laevis   و T. tritici  ایجاد می شود" +
                "که گونه اول در ايران انتشار بیشتری دارد.");
        title.addLevel("سطح تليوسپورها در T.laevis صاف، اما در T. tritici مشبك است.");
        title.addLevel("دانه های آلوده به دلیل داشتن ماده تری متیل آمین بوی ماهی گندیده می دهند و کیفیت نانوایی گندم را به شدت کاهش می دهند. ");
        menuItem.addTitle(title);
        title = new Title("مدیریت بیماری سیاهک پنهان معمولی گندم");
        title.addLevel("كاشت بذر سالم و گواهی شده.");
        title.addLevel("ضد عفوني دقیق بذر با استفاده از قارچ كش هاي توصیه شده");
        title.addLevel(" عمليات ضد عفوني بايد دقيق انجام شود، بنحوي كه پوشش يكنواخت و كاملي از سم تمام بذرها را دربرگيرد. اصولا فرمولاسيون هاي مايع پوشش یکنواختی از سم را در روی بذر ایجاد می کنند.");
        title.addLevel("قارچکشهای ثبت شده برای سیاهک پنهان معمولی گندم: رئال FS 20%، 2/0 ليتر در هزار، ديويدند FS 3% يا DS 3%، 1 در هزار،سومي ايت FS 2% يا WP 2%، 2 در هزار،ويتاواكس تيرام FL 40% يا WP 75%، 2 در هزار.، بايتان DS 7.5%، 2 کیلو گرم براي يك تن بذر،وينسيت  DS 5%، 2 کیلو گرم براي يك تن بذر.،لوسپل SD 12.5%، 3/0 ليتر براي يك تن بذر،لاماردور FS 40%، 2/0 ليتر براي يك تن بذر،راكسيل FS 6% 5/0 ليتر يا DS 2%، 5/1 درهزار ");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("سياهك پنهان پاكوتاه", ContextCompat.getDrawable(context, R.drawable.img_11));
        title = new Title("شرح");
        title.addLevel("قارچ عامل Tilletia controversa Kuhn     ");
        title.addLevel("در ايران اولین بار در سال  1364 گزارش گرديد");
        title.addLevel("مناطق انتشار: كردستان، آذربايجان شرقي، آذربايجان غربي، همدان، اردبيل، زنجان و لرستان");
        title.addLevel("محدود به مناطقی است که دارای یک دوره طولانی پوشش برفی هستند.");
        title.addLevel("قارچ عامل بیماری در خاک 5-4 سال زنده باقی می ماند.");
        title.addLevel("دمای مناسب برای جوانه زنی اسپورها 7-3 درجه سانتی گراد است");
        title.addLevel("اسپور های T. controversa بعد از 6-3 هفته جوانه می زنند ولی اسپورهای سیاهک معمولی بعد از سه روز جوانه می زنند. ");
        menuItem.addTitle(title);
        title = new Title("علایم بیماری سیاهک پنهان پاکوتاه گندم");
        title.addLevel("علائم ظاهري: كوتولگي بوته، افزايش تعداد پنجه، و وجود لکه های زرد رنگ در برگ در اوایل فصل رشد (Flecking)");
        title.addLevel("باز شدن ریشکهای خوشه های آلوده در مقایسه با خوشه های سالم");
        title.addLevel("دانه هاي آلوده  گرد و كروي شكل ميباشند. ");
        title.addLevel("سورها حاوی میلیونها اسپور قارچ می باشند که در هنگام برداشت و خرمنکوبی در محیط پخش می شوند ");
        title.addLevel("آلودگی مجددا در پاییز هنگام پنجه زنی اتفاق می افتد ");
        menuItem.addTitle(title);
        title = new Title("روشهاي كنترل بيماري سیاهک پنهان پاکوتاه");
        title.addLevel("استفاده از بذر سالم و گواهي شده ");
        title.addLevel("ضدعفوني بذر با قارچكشهاي موثر نظير:ديويدند FS 3%، 1 ليتر يا DS 3%، 2 كيلوگرم براي يك تن بذر،تكتو WP 60%، 25/1 كيلو گرم براي يك تن بذر. ");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("سياهك ناقص (هندی) گندم", ContextCompat.getDrawable(context, R.drawable.img_12));
        title = new Title("شرح");
        title.addLevel("سياهك ناقص گندم كه توسط  قارچ عاملTilletia indica   اولين بار در سال 1931از هند گزارش گرديد.");
        title.addLevel("مناطق انتشار: علاوه بر هند از  پاكستان (1975) ،افغانستان ، عراق ، سوريه ،  مكزيك (1972) ،  نپال (1989) و امريكا (1996) و اخيرا از آفريقاي جنوبي گزارش شده است.");
        title.addLevel("در سال 1375 از ايران در مناطق فارس، كرمان و هرمزگان گزارش شد.");
        title.addLevel("تاثير چنداني در کاهش مقدار محصول ندارد اما از دست دادن ارزش تجارتي گندم جهت صادرات آن به ساير كشورها و همچنين اعمال مقرارت قرنطينه داخلي و خارجي باعث ضرر و زيان اقتصادي هنگفتي مي گردد.");
        title.addLevel("اصولا محصول گندم با بيش از 3% آلودگي ارزش مصرف خوراكي ندارد و بوي نامطبوع مي دهد.");
        title.addLevel("دانه هاي آلوده به K.B اثرات سمي به انسان و حيوان ندارد ولي کیفیت نانوایی آرد به شدت پایین می آید. ");
        menuItem.addTitle(title);
        title = new Title("روشهای کنترل سیاهک ناقص");
        title.addLevel("اجراي قرنطينه به منظور ممانعت از انتقال بذور گندم مناطق آلوده به مناطق سالم");
        title.addLevel("كاشت گندم دوروم (ارقام دنا و بهرنگ) يا جو در مناطق آلوده");
        title.addLevel("كاشت بذور سالم و ضدعفونی شده با قارچکشهای موثر");
        title.addLevel("در صورت لزوم سمپاشي مزارع در مرحله متورم شدن خوشه ها با استفاده از قارچکشهای زیر انجام شود : تيلت EC 25%، 5/0 ليتر در هكتار، آلتو SL 10%، 5/0 ليتر در هكتار،فوليكور EW 25% ، 1 ليتر در هكتار");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("پوسیدگی معمولی ریشه گندم", ContextCompat.getDrawable(context, R.drawable.img_13));
        title = new Title("شرح");
        title.addLevel("عامل بیماری Bipolaris sorokiniana");
        title.addLevel("علایم بیماری در پوسیدگی معمولی ریشه اصلی سیاه می شود ولی در بوته های سالم تغییر رنگ دیده نمی شود.");
        title.addLevel("در پوسیدگی فوزاریومی کل ریشه های فرعی و اصلی تغییر رنگ می دهند");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem = new MenuItem("پوسیدگی فوزاریومی طوقه و ریشه", ContextCompat.getDrawable(context, R.drawable.img_14));
        title = new Title("شرح");
        title.addLevel("خوشه ها سفید رنگ دیده می شوند (white head).");
        title.addLevel("قسمت پایین ساقه به رنگ قهوه ای شکلاتی دیده میشود");
        title.addLevel("در قسمتهای غلاف برگهای پایینی یا طوقه پودر صورتی رنگ دیده می شود.");
        title.addLevel("در مزارعی که دچار تنشهای آبی می شوند شدت می یابند.در دیمات خسارت زیاد می زند.");
        title.addLevel("خسارت این بیماریها با مرور زمان افزایش پیدا می کند.");
        title.addLevel("اغلب دامنه میزبانی وسیعی در میان گرامینه ها دارند.");
        menuItem.addTitle(title);
        title = new Title("عامل بیماری");
        title.addLevel(":در ایران دو گونه غالب است: Fusarium culmorum و F. pseudograminearum");
        menuItem.addTitle(title);
        title=new Title("مدیریت بیماری");
        title.addLevel("جلوگیری از تنش های آبی در مرحله داشت");
        title.addLevel("رعایت تناوب گندم با دانه های روغنی و حبوبات");
        title.addLevel("ارقام گندم دورم خیلی حساس هستند");
        title.addLevel("استفاده از ارقام متحمل نظیر:پیشگام، میهن ، سیوند، دز،استار، کاسکوژن ، کاسپارد و الموت");
        title.addLevel("لاین C-87-18 از موسسه تحقیقات اصلاح و تهیه نهال و بذر مقاومت بسیار خوبی دارد. ");
        title.addLevel("ارقام خارجی شامل: GALA, Burbot-6, Sunco ");
        menuItem.addTitle(title);
        disease.add(menuItem);

        menuItem=new MenuItem("پاخوره گندم",ContextCompat.getDrawable(context, R.drawable.img_15));
        title=new Title("شرح");
        title.addLevel("علائم بارز بیماری سفید شدن خوشه های بوته های آلوده قبل از خو شه های سالم.");
        title.addLevel("ریشه های آلوده سیاه رنگ و براق می شوند به ویژه مغز ریشه سیاه رنگ دیده می شوند.");
        title.addLevel("در زیر بینوکلر میسیلیومهای سیاه رنگ که ریزومورف قارچ است در سطح ریشه های آلوده دیده می شوند");
        title.addLevel("بوته های آلوده براحتی از خاک کنده می شوند.");
        title.addLevel("بوته های آلوده در مزرعه بصورت ردیفی دیده می شوند");
        title.addLevel("با کشت مکرر گندم جمعیت آن در خاک سال به سال بیشتر می شود.");
        title.addLevel("شدت بیماری در خاکهای سنگین و قلیایی بیشتر است");
        menuItem.addTitle(title);
        title=new Title("مدیریت بیماری پاخوره گندم");
        title.addLevel("استفاده از تناوب زراعی با استفاده از گیاهان غیر میزبان نظیر کلزا ، چغندر قند و آیش به مدت حداقل یکسال");
        title.addLevel("از بین بردن گندم های خودرو و علفهای هرز گرامینه در زمان تناوب");
        title.addLevel("هیچ رقم مقاومی برای این بیماری وجود ندارد");
        title.addLevel("ضد عفوني بذور گندم با استفاده از قارچكش هاي: پروپیکونازول 2 در هزار و تریادیمنول 3/0 در هزار بمنظور كاهش بيماري پاخوره گندم.");
        menuItem.addTitle(title);
        disease.add(menuItem);



    }
}
